name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install black flake8 pytest twine

      - name: Run linters
        run: |
          black --check .
          flake8 .

      - name: Run tests
        run: pytest

      - name: Determine package version
        id: version
        run: echo ::set-output name=version::$(python setup.py --version)

      - name: Generate changelog
        uses: release-drafter/release-drafter@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-template: v${{ formatNumber(nextVersion.major) }}.${{ formatNumber(nextVersion.minor) }}.${{ formatNumber(nextVersion.patch) }}
          template: |
            ## Changes
            {% for group in groups -%}
            ### {{ group.title }}
            {% for note in group.notes -%}
            - {{ note.title }}
            {% endfor -%}
            {% endfor %}
          change-template: '- {{message}} (@{{author}})'
          change-labels: |
            - 'enhancement'
            - 'bug'
          exclude-labels: 'ci-*'

      - name: Create version tag
        run: |
          git tag -a "v${{ steps.version.outputs.version }}" -m "Version ${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
