name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install black flake8 pytest twine

      - name: Run linters
        run: |
          black --check .
          flake8 .

      - name: Run tests
        run: pytest

      - name: Determine package version
        id: version
        run: echo ::set-output name=version::$(python setup.py --version)

      - name: Generate changelog
        uses: mathieudutour/github-tag-action@v6.3.0
        id: tag_and_changelog
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: patch
          changelog_sections: |
            Features: Features and User Stories
            Bug Fixes: Bug Fixes and Hotfixes
            Performance Improvements: Performance Improvements
            Maintenance: Maintenance and Cleanup
          changelog_exclude_labels: ci-*

      - name: Create version tag
        run: |
          git tag -a "v${{ steps.tag_and_changelog.outputs.new_tag }}" -m "Version ${{ steps.tag_and_changelog.outputs.new_tag }}"
          git push origin "v${{ steps.tag_and_changelog.outputs.new_tag }}"

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
