name: PR Checks

on:
  pull_request:
  pull_request_target:

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.reviews.nodes[0].authorAssociation == 'OWNER'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install black flake8 pytest

      - name: Check code formatting and style
        run: |
          black --check .
          flake8 .

      - name: Run tests
        run: pytest
